name: nqm_fairseq
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cryptography=3.4.7
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.3.0
  - ffmpeg=4.3
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.0
  - gmp=6.2.1
  - gnutls=3.6.5
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isodate=0.6.0
  - jedi=0.18.0
  - jinja2=2.11.2
  - joblib=1.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.4.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keepalive=0.5
  - lame=3.100
  - lcms2=2.11
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=4.0.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - nettle=3.4.1
  - ninja=1.10.2
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - packaging=20.4
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.8.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.8.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - rdflib=5.0.0
  - readline=8.1
  - requests=2.25.1
  - sacremoses=0.0.43
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sparqlwrapper=1.8.5
  - sqlite=3.35.2
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.0.4
  - tqdm=4.59.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - antlr4-python3-runtime==4.8
    - cython==0.29.22
    - dataclasses==0.6
    - fairseq==0.10.2
    - hydra-core==1.0.6
    - importlib-resources==5.1.2
    - omegaconf==2.0.6
    - portalocker==2.0.0
    - protobuf==3.15.8
    - pyyaml==5.4.1
    - regex==2021.3.17
    - sacrebleu==1.5.1
    - subword-nmt==0.3.7
    - tensorboardx==2.2
