name: fairseq_local
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8.8
  - rdflib
  - openpyxl
  - scikit-learn
  - sacremoses
  - pip
  - torchaudio
  - torchvision
  - pytorch
  - pandas
  - numpy==1.19.5
  - sentencepiece
  - tensorboardx
  - editdistance